baseURL = 'https://stik.world/'
languageCode = 'en-us'
title = 'Everything is social'
theme = "stik"
DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = "false"
disableHugoGeneratorInject = "true"
enableRobotsTXT = "true"

[languages]
    [languages.en]
        languageName = "English"
        weight = 1
    [languages.es]
        languageName = "Español"
        weight = 2
